
# Quarkus configuration
quarkus:
  http:
    host: 127.0.0.1
    port: 9000
    cors:
      ~: true
      origins: "/.*/"

  log:
    file:
      enable: true
      path: "../application.log"
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n"

# Compeition configuration
competition:
  file-location: /home/matthew/images/Named