
# Quarkus configuration
quarkus:
  http:
    host: 127.0.0.1
    port: 9000
    cors:
      ~: true
      origins: "/.*/"

# Compeition configuration
competition:
  file-location: /home/matthew/images/Named