
# Quarkus configuration
quarkus:
  http:
    host: 127.0.0.1
    port: 9000
    cors:
      ~: true
      origins: "/.*/"

  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n"
    file:
      enable: true
      path: "logs/ospreycompetition.log"
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n"
      rotation:
        file-suffix: ".yyyy-MM-dd"

# Compeition configuration
competition:
  file-location: /home/matthew/images/Named